name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dependabot-auto-merge:
    uses: brainxio/workflows/.github/workflows/dependabot-auto-merge.yml@main